# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08b6d00ec9ddd8ee4256e4fc3b5c024cb0c486678f85694833885e72a1d8d288e7cc6d0898b4009eba87ed2240cb138150ee085c2621a245b611e5d3f4404e3f

test:
  secret_key_base: c82ce39e93571221c0d7b0dc8c9a10dfd062806cd69ed4c535ef5d5595b7eb73bd4f109ab420dbde87d2e8196f3c32af22608aa31ed4bbdd4c1904f9368b4893

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
